language: go
go_import_path: github.com/bketelsen/golo
go:
  - 1.x
  - tip

sudo: false

install:
  - true

script:
  - go build -o $HOME/golo-v github.com/bketelsen/golo/cmd/golo
  - $HOME/golo
  - $HOME/golo
